inventario_bodega/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', TemplateView.as_view(template_name="index.html"), name='index'),
    url(r'users/', include('users.urls', namespace='users')),
    url(r'recursos/', include('recursos.urls', namespace='recursos')),
]+ static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)

recursos/urls.py
from django.conf.urls import url, include
from recursos.views import *

urlpatterns = [
     url(r'^$', RecursoCreateView.as_view(), name='create_recurso'),
     url(r'lista/', RecursoListView.as_view(), name='list_recurso'),
     url(r'asignar/(?P<id>\d+)/$', RecursoAddView.as_view(), name='add_recurso'),
     url(r'asignar/(?P<recurso_id>\d+)/(?P<persona_id>[0-9]+)$', asg_recurso, name='asg_recurso'),
     url(r'delete/(?P<recurso_id>\d+)/(?P<persona_id>[0-9]+)$', delete_recurso, name='delete_recurso'),
     url(r'editar/(?P<id>\d+)/$', RecursoUpdateView.as_view(), name='update_recurso'),
]

users/urls.py
from django.conf.urls import url, include
from users.views import PersonaCreateView, PersonaView, PersonaListView


urlpatterns = [
     url(r'^$', PersonaCreateView.as_view(), name='create_persona'),
     url(r'^lista/', PersonaListView.as_view(), name='list_persona'),
     url(r'^ver/(?P<id>\d+)/$', PersonaView.as_view(), name='persona_view'),
]

recursos/models.py
# -*- coding: utf-8 -*-
from django.db import models
from users.models import Persona
# Create your models here.


class Categoria(models.Model):
    nombre=models.CharField(max_length=30, verbose_name='nombre')

    def __str__(self):
        return self.nombre


class Recurso(models.Model):
    nombre=models.CharField(max_length=30, verbose_name='nombre')
    codigo=models.CharField(max_length=5, verbose_name='codigo')
    marca=models.CharField(max_length=15, verbose_name='marca')
    categoria=models.ForeignKey(Categoria, on_delete=models.CASCADE, blank=True, null=True)
    persona_asignada=models.ForeignKey(Persona, on_delete=models.CASCADE, blank=True, null=True)
    fecha_asignacion=models.DateTimeField(auto_now_add=True, blank=True)

    def __str__(self):
        return self.nombre

users/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

# Create your models here.
class Persona(User):
    identificacion=models.IntegerField(blank=False, null=False)
    fecha_registro=models.DateTimeField(auto_now_add=True, blank=True)

    def __str__(self):
        return self.username

recursos/forms.py
from django import forms
from django.forms import ModelForm
from recursos.models import Recurso


class RecursoForm(ModelForm):
    # email = forms.EmailInput(attrs={'id':"inputEmail"})
    class Meta:
        model=Recurso
        exclude=['codigo', 'fecha_asignacion']
        fields=['nombre', 'marca', 'categoria', 'persona_asignada',]

class RecursoUpdateForm(ModelForm):
    class Meta:
        model=Recurso
        fields=['nombre', 'marca', 'categoria', 'persona_asignada',]

users/forms.py
from django import forms
from django.forms import ModelForm
from users.models import Persona

class PersonaForm(ModelForm):
    email = forms.EmailInput(attrs={'id':"inputEmail"})
    class Meta:
        model=Persona
        exclude=['username', 'password', 'is_active', 'last_login', 'groups', 'user_permissions', 'is_staff', 'date_joined', 'is_superuser', 'fecha_registro']
        fields=['first_name', 'last_name', 'identificacion', 'email']

recursos/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from recursos.models import Recurso
from users.models import Persona
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.list import ListView
from recursos.forms import RecursoForm, RecursoUpdateForm
from django.views.generic.base import TemplateView
import string
import random
import datetime

# Create your views here.

def id_generator(size, chars=string.ascii_uppercase + string.digits):
     return str(''.join(random.choice(chars) for _ in range(size)))

class RecursoCreateView(CreateView):
    model=Recurso
    form_class= RecursoForm
    template_name='recursos/recursos.html'
    success_url = reverse_lazy('recursos:list_recurso')

    def form_valid(self, form):
        recurso = form.save(commit=False)
        recurso.codigo = id_generator(4)
        form.save()
        return super(RecursoCreateView, self).form_valid(form)

class RecursoListView(ListView):
    model=Recurso
    paginate_by= 10
    template_name= 'recursos/recursos_list.html'
    context_object_name = 'recursos'

    def get_context_data(self, **kwargs):
        context = super(RecursoListView, self).get_context_data(**kwargs)
        recursos= Recurso.objects.all()
        context['recursos'] = recursos
        context['is_real']=True
        return context

class RecursoUpdateView(UpdateView):
    model=Recurso
    form_class=RecursoUpdateForm
    template_name='recursos/recursos.html'
    success_url = reverse_lazy('recursos:list_recurso')

    def get_object(self, queryset=None):
        obj = Recurso.objects.get(pk=self.kwargs['id'])
        return obj

    def form_valid(self, form):
        recurso = form.save(commit=False)
        recurso.fecha_asignacion = datetime.datetime.now()
        form.save()
        return super(RecursoUpdateView, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context=super(RecursoUpdateView, self).get_context_data(**kwargs)
        context['recurso']=Recurso.objects.get(pk=self.kwargs['id'])
        context['is_update'] = True
        return context


def asg_recurso(request, recurso_id, persona_id):
    recurso = Recurso.objects.get(pk=recurso_id)
    persona = Persona.objects.get(pk=persona_id)
    recurso.persona_asignada = persona
    recurso.save()
    return redirect('users:persona_view', id=persona_id)

def delete_recurso(request, recurso_id, persona_id):
    persona = Persona.objects.get(pk=persona_id)
    recurso = Recurso.objects.get(pk=recurso_id)
    recurso.persona_asignada = None
    recurso.save()
    return redirect('users:persona_view', id=persona_id)


class RecursoAddView(TemplateView):
    template_name= 'recursos/recursos_list.html'

    def get_context_data(self, **kwargs):
        context =super(RecursoAddView, self).get_context_data(**kwargs)
        recursos= Recurso.objects.exclude(persona_asignada__pk=self.kwargs['id'])
        persona = Persona.objects.get(pk=self.kwargs['id'])
        context['recursos'] = recursos
        context['persona']=persona
        context['is_add']=True
        return context

users/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from users.models import Persona
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.list import ListView
from django.views.generic.base import TemplateView
from users.forms import PersonaForm

# Create your views here.
class PersonaCreateView(CreateView):
    model=Persona
    form_class=PersonaForm
    template_name='users/persona.html'
    success_url = reverse_lazy('users:list_persona')

    def form_valid(self, form):
        persona =form.save(commit=False)
        persona.username=persona.email
        form.save()
        return super(PersonaCreateView, self).form_valid(form)


class PersonaListView(ListView):
    model=Persona
    template_name= 'users/personas_list.html'

    def get_context_data(self, **kwargs):
        context = super(PersonaListView, self).get_context_data(**kwargs)
        context['personas'] = Persona.objects.all()
        return context


class PersonaView(TemplateView):
    template_name = 'users/persona_view.html'

    def get_context_data(self, *args, **kwargs):
        context = super(PersonaView, self).get_context_data(*args, **kwargs)
        persona = Persona.objects.get(pk=self.kwargs['id'])
        articulos = persona.recurso_set.all()
        context['persona'] = persona
        context['articulos'] = articulos
        #context['add_recurso'] = True
        return context

templates/blank.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>{% block title %}{% endblock %}</title>

  <!-- Custom fonts for this template-->
  <link href="{% static "vendor/fontawesome-free/css/all.min.css" %}" rel="stylesheet" type="text/css">
  <!-- Page level plugin CSS-->
  <link href="{% static "vendor/datatables/dataTables.bootstrap4.css"%}" rel="stylesheet">
  <!-- Custom styles for this template-->
  <link href="{% static "css/sb-admin.css"%}" rel="stylesheet">
  {% block head %}
  {% endblock %}
</head>

<body id="page-top">
   {% include "navbar.html" %}
  <div id="wrapper">
    <!-- Sidebar -->
     {% include "sidebar.html" %}

    <div id="content-wrapper">
      <div class="container-fluid">
        <!-- Breadcrumbs-->
        <ol class="breadcrumb">
          <li class="breadcrumb-item">
            <a href="{% url 'index' %}">Gestion de Inventario</a>
          </li>
        </ol>
        <!-- Page Content -->
        {% block content %}
        {% endblock %}
      </div>
      <!-- /.container-fluid -->
      <!-- Sticky Footer -->
      <footer class="sticky-footer">
        <div class="container my-auto">
          <div class="copyright text-center my-auto">
            <span>Copyright © Your Website 2019</span>
          </div>
        </div>
      </footer>
    </div>
    <!-- /.content-wrapper -->
  </div>
  <!-- /#wrapper -->

  <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>

  <!-- Bootstrap core JavaScript-->
  <script src="{% static "vendor/jquery/jquery.min.js"%}"></script>
  <script src="{% static "vendor/bootstrap/js/bootstrap.bundle.min.js"%}"></script>
  <script src="{% static "vendor/datatables/jquery.dataTables.min.js"%}"></script>
  <script src="{% static "vendor/datatables/dataTables.bootstrap4.js" %}"></script>

  <!-- Core plugin JavaScript-->
  <script src="{% static "vendor/jquery-easing/jquery.easing.min.js" %}"></script>
  <!-- Custom scripts for all pages-->
  <script src="{% static "js/sb-admin.min.js" %}"></script>
  <script src="{% static "js/demo/datatables-demo.js" %}
  "></script>
  {% block js %}
  {% endblock js %}

</body>

</html>

templates/index.html
{% extends 'blank.html' %}
{% load bootstrap_tags %}
{% block content %}
<h1>Modulos para la gestion de personas y recursos</h1>
<hr>
<div class="row">
      <div class="col-xl-6 col-sm-6 mb-3">
        <div class="card text-white bg-primary o-hidden h-100">
          <div class="card-body">
            <div class="card-body-icon">
              <i class="fas fa-fw fa-list"></i>
            </div>
            <div class="mr-5">Modulo de Personas</div>
          </div>
          <a class="card-footer text-white clearfix small z-1" href="{% url 'users:list_persona'%}">
              <span class="float-left">Lista de Personas</span>
              <span class="float-right"><i class="fas fa-clipboard-list fa-2x"></i></span>
          </a>
          <a class="card-footer text-white clearfix small z-1" href="{% url 'users:create_persona'%}">
            <span class="float-left">Crear Persona</span>
            <span class="float-right"><i class="fas fa-user-plus fa-2x"></i></span>
          </a>
        </div>
      </div>
      <div class="col-xl-6 col-sm-6 mb-3">
        <div class="card text-white bg-warning o-hidden h-100">
          <div class="card-body">
            <div class="card-body-icon">
              <i class="fas fa-fw fa-list"></i>
            </div>
            <div class="mr-5">Modulo de Recursos</div>
          </div>
          <a class="card-footer text-white clearfix small z-1" href="{% url 'recursos:list_recurso'%}">
            <span class="float-left">Lista de Recursos</span>
            <span class="float-right"><i class="fas fa-clipboard-list fa-2x"></i></span>
          </a>
          <a class="card-footer text-white clearfix small z-1" href="{% url 'recursos:create_recurso'%}">
            <span class="float-left">Crear Recursos</span>
            <span class="float-right"><i class="fas fa-plus-square fa-2x"></i></span>
          </a>
        </div>
      </div>
      </div>
    </div>
{% endblock%}

templates/navbar.html
<nav class="navbar navbar-expand navbar-dark bg-dark static-top">

  <a class="navbar-brand mr-1" href="{% url 'index' %}">Gestion de Inventario</a>

  <button class="btn btn-link btn-sm text-white order-1 order-sm-0" id="sidebarToggle" href="#">
    <i class="fas fa-bars"></i>
  </button>
</nav>

templates/recursos/recursos.html
{% extends 'blank.html' %}
{% load bootstrap_tags %}

{% block content %}
<div class="container">
  <div class="card card-register mx-auto mt-5">
    {% if is_update %}
        <div class="card-header">Editar Recursos</div>
        {% else %}
        <div class="card-header">Registrar Recursos</div>
    {% endif %}

    <div class="card-body">
      <form action="" method="post" enctype="multipart/form-data">
        <div class="form-group">
          {% csrf_token %}
            {{ form|as_bootstrap }}
        </div>
         <input type="submit" value="Guardar" class="btn btn-primary btn-block">
      </form>
    </div>
  </div>
</div>
{% endblock %}

templates/recursos/recursos_list.html
{% extends 'blank.html' %}
{% load bootstrap_tags %}

{% block content %}
<div class="card mb-3">
      <div class="card-header">
        <a href="{% url 'recursos:create_recurso' %}"><i class="fas fa-plus-square"></i></a> Agregar Recurso
        {% if is_add %}
        Asignar Recurso a: {{persona}}
        {% endif %}
      </div>
      <div class="card-body">
        <div class="table-responsive">
          <table class="table table-bordered" id="tabla" width="100%" cellspacing="0">
            <thead>
              <tr>
                <th>CODIGO</th>
                <th>NOMBRE</th>
                <th>CATEGORIA</th>
                <th>MARCA</th>
                <th>ASIGNADO A</th>
                <th>FECHA DE ASIGANCION</th>
                <th>OPCIONES</th>
              </tr>
            </thead>
            <tfoot>
              <tr>
                <th>CODIGO</th>
                <th>NOMBRE</th>
                <th>CATEGORIA</th>
                <th>MARCA</th>
                <th>ASIGNADO A</th>
                <th>FECHA DE ASIGANCION</th>
                <th>OPCIONES</th>
              </tr>
            </tfoot>
            <tbody>
              {% for recurso in recursos %}
              <tr>
                <td>{{recurso.codigo}}</td>
                <td>{{recurso.nombre}}</td>
                <td>{{recurso.categoria}}</td>
                <td>{{recurso.marca}}</td>
                <td>{{recurso.persona_asignada}}</td>
                <td>{{recurso.fecha_asignacion}}</td>
                {% if is_add %}
                  <td><a href="{% url 'recursos:asg_recurso' recurso_id=recurso.id persona_id=persona.id %}"><i class="fas fa-plus-square"></i></a></td>
                {% else %}
                  <td><a href="{% url 'recursos:update_recurso' id=recurso.id %}"><i class="fas fa-pen-square"></i></a></td>
                {% endif %}

              </tr>
            {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
      <div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div>
    </div>
{% endblock %}

{% block js %}

<script>
$(document).ready(function()
{
    var table = $('#tabla').DataTable( {
        "language": {
            url: "/static/localizacion/es_ES.json"
        }
    } );

    $('#tabla tbody').on( 'click', 'tr', function()
    {
        if ($(this).hasClass('selected') )
        {
            $(this).removeClass('selected');

        }
        else
        {
            table.$('tr.selected').removeClass('selected');
            $(this).addClass('selected');
        }
    });

});
</script>
{% endblock js %}

templates/sidebar.html
<ul class="sidebar navbar-nav">
  <li class="nav-item">
    <a class="nav-link" href="{% url 'users:list_persona' %}">
      <i class="fas fa-users-cog"></i>
      <span>Personas</span>
    </a>
  </li>

  <li class="nav-item">
    <a class="nav-link" href="{% url 'recursos:list_recurso' %}">
      <i class="fas fa-tools"></i>
      <span>Recursos</span></a>
  </li>
</ul>

templates/users/persona.html
{% extends 'blank.html' %}
{% load bootstrap_tags %}

{% block content %}
<div class="container">
  <div class="card card-register mx-auto mt-5">
    <div class="card-header">Registrar Personas</div>
    <div class="card-body">
      <form action="" method="post" enctype="multipart/form-data">
        <div class="form-group">
          {% csrf_token %}
            {{ form|as_bootstrap }}
        </div>
         <input type="submit" value="Guardar" class="btn btn-primary btn-block">
      </form>
    </div>
  </div>
</div>
{% endblock %}

templates/users/persona_view.html
{% extends 'blank.html' %}


{% block content %}
<div class="container">
  <div class="card mb-3">
    <div class="card-header">Detalles</div>
    <div class="card-body">
      <table style="width:45%">
        <tr>
          <th>Nombre:</th>
          <th>{{persona.first_name}}</th>
        </tr>
        <tr>
          <th>Apellido:</th>
          <th>{{persona.last_name}}</th>
        </tr>
        <tr>
          <th>Identificacion: </th>
          <th>{{persona.identificacion}}</th>
        </tr>
        <tr>
          <th>Email: </th>
          <th>{{persona.email}}</th>
        </tr>
        <tr>
          <th>Agregar Recurso <a href="{% url 'recursos:add_recurso' id=persona.id %}"><i class="fas fa-plus-square"></i></a></th>
        </tr>
      </table>
    </div>
  </div>
</div>
<div class="container">
  <div class="card mb-3">
    <div class="card-body">
      <div class="table-responsive">
        <table class="table table-bordered" id="tabla" width="100%" cellspacing="0">
          <thead>
            <tr>
              <th>CODIGO</th>
              <th>NOMBRE</th>
              <th>CATEGORIA</th>
              <th>MARCA</th>
              <th>FECHA DE ASIGANCION</th>
              <th>OPCIONES</th>
            </tr>
          </thead>
          <tfoot>
            <tr>
              <th>CODIGO</th>
              <th>NOMBRE</th>
              <th>CATEGORIA</th>
              <th>MARCA</th>
              <th>FECHA DE ASIGANCION</th>
              <th>OPCIONES</th>
            </tr>
          </tfoot>
          <tbody>
            {% for a in articulos %}
            <tr>
              <td>{{a.codigo}}</td>
              <td>{{a.nombre}}</td>
              <td>{{a.categoria}}</td>
              <td>{{a.marca}}</td>
              <td>{{a.fecha_asignacion}}</td>
              <td><a href="{% url 'recursos:delete_recurso' recurso_id=a.id persona_id=persona.id %}"><i class="fas fa-trash-alt"></i></a></td>
            </tr>
          {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% block js %}

<script>
$(document).ready(function()
{
    var table = $('#tabla').DataTable( {
        "language": {
            url: "/static/localizacion/es_ES.json"
        }
    } );

    $('#tabla tbody').on( 'click', 'tr', function()
    {
        if ($(this).hasClass('selected') )
        {
            $(this).removeClass('selected');

        }
        else
        {
            table.$('tr.selected').removeClass('selected');
            $(this).addClass('selected');
        }
    });

});
</script>
{% endblock js %}

templates/users/personas_list.html
{% extends 'blank.html' %}
{% load static %}

{% block content %}
<div class="card mb-3">
      <div class="card-header">
        <a href="{% url 'users:create_persona' %}"><i class="fas fa-user-plus"></i></a>
        Registrar Personas
      </div>
      <div class="card-body">
        <div class="table-responsive">
          <table class="table table-bordered" id="tabla" width="100%" cellspacing="0">
            <thead>
              <tr>
                <th>NOMBRE</th>
                <th>APELLIDO</th>
                <th>IDENTIFICACION</th>
                <th>EMAIL</th>
                <th>DETALLE</th>
              </tr>
            </thead>
            <tfoot>
              <tr>
                <th>NOMBRE</th>
                <th>APELLIDO</th>
                <th>IDENTIFICACION</th>
                <th>EMAIL</th>
                <th>DETALLE</th>
              </tr>
            </tfoot>
            <tbody>
              {% for persona in personas %}
              <tr>
                <td>{{persona.first_name}}</td>
                <td>{{persona.last_name}}</td>
                <td>{{persona.identificacion}}</td>
                <td>{{persona.email}}</td>
                <td><a href="{% url 'users:persona_view' id=persona.id %}"><i class="fas fa-info-circle"></i></a></td>
              </tr>
            {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
      <div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div>
    </div>
{% endblock %}

{% block js %}

<script>
$(document).ready(function()
{
    var table = $('#tabla').DataTable( {
        "language": {
            url: "/static/localizacion/es_ES.json"
        }
    } );

    $('#tabla tbody').on( 'click', 'tr', function()
    {
        if ($(this).hasClass('selected') )
        {
            $(this).removeClass('selected');

        }
        else
        {
            table.$('tr.selected').removeClass('selected');
            $(this).addClass('selected');
        }
    });

});
</script>
{% endblock js %}